name: Build APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If the project is inside TodoOfflineApp-android/, move it up to repo root
      - name: Bring project to repo root
        shell: bash
        run: |
          set -e
          echo "Initial files at repo root:"
          ls -la
          if [ -d "TodoOfflineApp-android" ]; then
            shopt -s dotglob
            mv TodoOfflineApp-android/* .
            rm -rf TodoOfflineApp-android
          fi
          echo "After move to root:"
          ls -la
          # Sanity check that a Gradle project exists
          if [ ! -f "settings.gradle.kts" ] && [ ! -f "settings.gradle" ]; then
            echo "ERROR: settings.gradle(.kts) not found at repo root."
            exit 1
          fi

      - name: Show gradle.properties (must contain AndroidX flags)
        run: |
          if [ -f gradle.properties ]; then
            echo "===== gradle.properties ====="
            cat gradle.properties
          else
            echo "gradle.properties is missing at repo root!"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses + install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Point Gradle to SDK
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.7"

      - name: Ensure wrapper & print versions
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew
          ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
