name: Build APK (Debug)
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TodoOfflineApp-android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Gradle 8.7
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      - name: Generate Gradle wrapper
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle wrapper --gradle-version 8.7

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: TodoOfflineApp-android/app/build/outputs/apk/debug/app-debug.apk
